### ISSUE TITLE
Error when creating kitty

### ISSUE THREAD

**Issue by jimmychu0807** [shawntabrizi/substratekitties#7]
On the latest `v2.0` branch, when creating kitty from polkadot-JS app, it returns in the browser dev-console:
```
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckEra.0: Client(Execution(ApiError("Could
```

The runtime console:
```
2019-11-27 16:34:06 Idle (0 peers), best: #50 (0x95d8…39c0), finalized #48 (0x45ff…1a14), ⬇ 0 ⬆ 0
2019-11-27 16:34:09 Failed to submit extrinsic: Extrinsic verification error: Execution: Could not convert parameter `tx` between node and runtime: Error decoding field CheckEra.0
```

I and @kaichaosun encounter this issue.

**Comment by ltfschoen** [comment]
We've been discussing this issue in the Substrate Technical (Public) Riot chatroom.
It's because all the dependencies are being build from an old commit dated 25th October in the 'master' branch of the Substrate repo. I've got it to work by using the latest commit instead (i.e. progressively going through all the commits since then and getting it to compile), and then checking that it was consistent with the https://github.com/paritytech/substrate/tree/master/bin/node-template 

I'll transfer the changes I had to make across to this template

**Comment by ltfschoen** [comment]
Solution: https://github.com/ltfschoen/substratekitties/tree/v2.0

Noting that this fix likely won't get merged https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$1574898806602KyvWj:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=web3.foundation

**Comment by shawntabrizi** [comment]
stale
